name: Deploy

on:
  workflow_run:
    workflows: ['CI']
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}          # Your EC2 public IP or hostname in GitHub secrets
        username: ${{ secrets.SSH_USERNAME }}  # Your EC2 instance's SSH username (e.g., ec2-user, ubuntu)
        key: ${{ secrets.SSH_KEY }}            # Your SSH private key (in GitHub secrets)
        script: |
          sudo docker pull himanshudangwal/computer-vision:latest
          sudo docker stop computer-vision || true
          sudo docker rm computer-vision || true
          sudo docker run -d --name computer-vision -p 80:5173 himanshudangwal/computer-vision:latest
